#!/bin/bash

python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic --noinput --clear
export DJANGO_SETTINGS_MODULE=core.settings
pytest apps/restaurant/tests/
python manage.py runserver 0.0.0.0:8000