# Generated by Django 4.2 on 2023-04-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="count_of_votes",
            field=models.SmallIntegerField(default=0),
        ),
    ]
